name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Hub Mirror Action.
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/ljw1412
          dst: gitee/ljw1412
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: otaku-toolbox-plugins
          force_update: true
